### ISSUE TITLE
无法上网，错误日志如下

### ISSUE THREAD

**Issue by iulo** [jack80342/ShadowsocksX-NG-R#10]
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
  Referenced
 from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
  Referenced from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
  Referenced
 from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
  Referenced from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found

看起来是缺少了一些包，需要前置安装什么吗

**Comment by jack80342** [comment]
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
> Referenced
> from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
> Referenced from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
> Referenced
> from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.6.dylib
> Referenced from: /Users/username/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> 
> 看起来是缺少了一些包，需要前置安装什么吗

已修复。https://github.com/jack80342/ShadowsocksX-NG-R/releases/tag/1.6.6
