### ISSUE TITLE
My computer has no effect, the error log is as follows

### ISSUE THREAD

**Issue by ganhang** [jack80342/ShadowsocksX-NG-R#3]
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/xxx/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found

**Comment by jack80342** [comment]
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libev/lib/libev.4.dylib
> Referenced from: /Users/xxx/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found

应该是我启用了Hardened Runtime后，默认禁用DYLD Environment Variables导致的。

**Comment by jack80342** [comment]
@ganhang 修复了这个问题。https://github.com/jack80342/ShadowsocksX-NG-R/releases/tag/v1.6.2

**Comment by wantanmee** [comment]
使用1.6.2版本后，依然有相同的错误提示，

**Comment by jack80342** [comment]
> 使用1.6.2版本后，依然有相同的错误提示，

系统版本是多少？

**Comment by jack80342** [comment]
> 使用1.6.2版本后，依然有相同的错误提示，

试试看这两个命令
brew update
brew upgrade

**Comment by wantanmee** [comment]
> > 使用1.6.2版本后，依然有相同的错误提示，
> 
> 系统版本是多少？

11.2.3

**Comment by ganhang** [comment]
好的，我试试

**Comment by ganhang** [comment]
10.15.7版本的错误
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/
libsodium.23.dylib
  Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
  Reason: image not 
found

**Comment by jack80342** [comment]
> 10.15.7版本的错误
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
> Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
> Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
> Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/
> libsodium.23.dylib
> Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not found
> dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libsodium/lib/libsodium.23.dylib
> Referenced from: /Users/ganhang/Library/Application Support/ShadowsocksX-NG-R/ss-local
> Reason: image not
> found


看日志是缺少libsodium、libev，
`brew install libsodium`
`brew install libev`

<img width="391" alt="截屏2021-05-28 21 47 03" src="https://user-images.githubusercontent.com/8936903/119993783-8a6e1280-bffe-11eb-8d88-6e1ea1ca604d.png">

**Comment by jack80342** [comment]
@wantanmee 同楼上
