### ISSUE TITLE
不能上网呢

### ISSUE THREAD

**Issue by jun58** [jack80342/ShadowsocksX-NG-R#6]
一切配好了（我并不是小飞机新手）但是不能上网，日志是这样的
![image](https://user-images.githubusercontent.com/20509429/121515061-51329b00-ca1f-11eb-8e2b-1761114bde1f.png)

**Comment by jack80342** [comment]
> 一切配好了（我并不是小飞机新手）但是不能上网，日志是这样的
> 
> ![image](https://user-images.githubusercontent.com/20509429/121515061-51329b00-ca1f-11eb-8e2b-1761114bde1f.png)
> 
> 
看这个
https://github.com/jack80342/ShadowsocksX-NG-R/issues/3

**Comment by jun58** [comment]
> #3
https://github.com/jack80342/ShadowsocksX-NG-R/issues/3#issuecomment-850435480
我下载了这个但是log里面还是报找不到这个libev

**Comment by jun58** [comment]
楼主知道什么原因吗@jack80342

**Comment by jack80342** [comment]
> 楼主知道什么原因吗@jack80342

没找到原因(´･ω･`)

**Comment by jun58** [comment]
最新进展（上接[issue](https://github.com/jack80342/ShadowsocksX-NG-R/issues/7#issuecomment-869613575)）
我把libev copy了一份到 /usr/local/lib 发现ss-local是可以找到libev了（不知道为什么原来找的@@HOMEBREW_PREFIX@@/opt/libev/lib/libev.4.dylib 我看了是有的但是说找不到），但是报了 /usr/local/lib/libev.4.dylib: mach-o, but wrong architecture 的错误，这也是我能进展到的地方了，现在果断 转战 v2ray ，配了一上午之后可以用了，
暂时关闭这个issue，之后有进展之后再来挖坟
