### ISSUE TITLE
M1 Mac 打开应用就闪退

### ISSUE THREAD

**Issue by fanxiweni** [jack80342/ShadowsocksX-NG-R#8]
设备：M1 MacBookPro
系统：macOS Big Sur 11.2.3
问题描述：解压后打开应用就闪退了

**Comment by jack80342** [comment]
> 设备：M1 MacBookPro
> 
> 系统：macOS Big Sur 11.2.3
> 
> 问题描述：解压后打开应用就闪退了

还没有适配M1

**Comment by jack80342** [comment]
> 设备：M1 MacBookPro
> 系统：macOS Big Sur 11.2.3
> 问题描述：解压后打开应用就闪退了

M1适配好了
https://github.com/jack80342/ShadowsocksX-NG-R/releases/tag/v1.6.5

**Comment by kidoneself** [comment]
一样，打开闪退

**Comment by jack80342** [comment]
> 一样，打开闪退
> 
> 
> 
> 

手里没有M1的苹果电脑，只是打包了通用应用，目前应该没有完全适配
