### ISSUE TITLE
不是M1，打开也闪退

### ISSUE THREAD

**Issue by imxp** [jack80342/ShadowsocksX-NG-R#9]
设备：MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
系统：macOS Big Sur 11.4
问题描述：解压后打开应用就闪退了

**Comment by jack80342** [comment]
> 设备：MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
> 
> 系统：macOS Big Sur 11.4
> 
> 问题描述：解压后打开应用就闪退了

求帮忙修一下，谢谢(´･ω･`)
